#!/bin/sh

# check the Security chip if we run on a WeTek device
  lsusb -d 096e:0006 &> /dev/null
  LSUSB_RET=$?

if [ -f /boot/remote.conf ]; then
  /usr/bin/remotecfg /boot/remote.conf
elif [ -f /etc/amremote/remote.conf ]; then
  /usr/bin/remotecfg /etc/amremote/remote.conf
elif [ "$LSUSB_RET" = 0 ]; then
  /usr/bin/remotecfg /etc/amremote/wetek.conf
elif [ "$LSUSB_RET" = 1 ]; then
  /usr/bin/remotecfg /etc/amremote/libreelec.conf
fi
