#!/bin/sh

export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-
export PATH=/opt/gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu/bin/:$PATH

export KERNEL_SRC=/home/user/armbian/sources/LINUX_DEFAULT/armbian

#CONFIG_CLD_HL_SDIO_CORE=y make

make clean
